name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ['3.2', '3.1', '2.7']

    steps:
    - name: "☁️ checkout repository"
      uses: actions/checkout@v3

    - name: "📦 install dependencies"
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: "📀 building"
      run: bundle exec rake transform:icons

    - name: "🚦 upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: phosphoricons-build
        path: ./lib/build

    - name: "🔍 run tests"
      run: bundle exec rake
